<?php
return [
    'pegawai' => [
        'Employee Code',
        'Name',
        'Status',
        'Status Desc',
        'Work Location',
        'Physical Location',
        'Departemen',
        'First Position',
        'Old Position',
        'New Position',
        'First Kode Posisi',
        'Old Kode Posisi',
        'New Kode Posisi',
        'Grade',
        'Grade Desc',
        'Peringkat Pegawai',
        'Hire Date',
        'Employee Type',
        'POH',
        'Work Phone No',
        'Email',
        'Personal Email',
        'Birth Country',
        'Usia',
        'Range Usia',
        'Jenis Kelamin',
        'Agama',
        'Golongan Darah',
        'Pendidikan',
        'No KTP',
        'No KK',
        'No BPJSTK',
        'No BPJSKES',
        'No NPWP',
        'Alamat',
        'Desa',
        'Kecamatan',
        'Lawang Kidul',
        'Kota',
        'Muara Enim',
        'Provinsi',
        'Sumatera Selatan',
        'Status Kawin',
        'Suami Atau Istri',
        'Spouse Birtdate',
        'Spouse Gender',
        'A1',
        'A1 BDATE',
        'A1 GENDER',
        'A2',
        'A2 BDATE',
        'A2 GENDER',
        'A3',
        'A3 BDATE',
        'A3 GENDER',
        'Nama Ayah',
        'Ayah BDATE',
        'Nama Ibu',
        'IBU BDATE',
        'Nama Ayah Mertua',
        'AYAH MERTUA BDATE',
        'Nama Ibu Mertua',
        'Ibu Mertua BDATE',
        'Updated At',
    ]
];
